// Product catalogue — the single source for every product page, card, sitemap
// entry, JSON-LD block, search index, MCP tool and JSON API response.
//
// Prices are AUD per pack and were set from Sydney halal-butcher market research
// (October 2026, see docs/PROJECT.md → "Pricing basis"), discounted for depot
// bulk packs. The owner should review them before launch.
//
// Images: every product points at /images/products/<slug>-<IMAGE_VERSION>.webp.
// Bump IMAGE_VERSION whenever images are regenerated so no cache serves old ones. Until real
// photos are supplied, scripts/images.mjs generates a branded placeholder at
// that exact path — dropping a real photo into assets/product-photos/<slug>.jpg
// and running `npm run images` replaces it with no code change.

export const IMAGE_VERSION = 'v2'
export const categoryImage = (slug) => `${slug}-${IMAGE_VERSION}.webp`
// Anchor id for a subcategory section on its category page (/shop/<cat>/#<subSlug>).
export const subSlug = (sub) => sub.toLowerCase().replace(/&/g, 'and').replace(/\+/g, '-plus').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

export const CATEGORIES = [
  {
    slug: 'beef',
    name: 'Beef',
    kw: 'halal beef',
    tagline: 'Primals, steaks, mince, Wagyu and soup bones',
    intro:
      'Halal beef for home kitchens, grill restaurants and caterers — from whole eye fillets and rumps to bulk mince, diced beef and Wagyu marble score 8–9. Every cut is packed in vacuum-sealed packs at depot prices and certified halal by Halal Control Australia.',
    subcategories: [
      'Primal Cuts & Loins',
      'Scotch & Ribeye Steaks',
      'Porterhouse & T-Bone',
      'Briskets & Short Ribs',
      'Mince, Diced & Stir-Fry',
      'Wagyu MB7+ & MB9+',
      'Shanks, Oxtail & Soup Bones',
    ],
  },
  {
    slug: 'lamb',
    name: 'Lamb',
    kw: 'halal lamb',
    tagline: 'Whole carcasses, cutlets, legs, shanks and curry cuts',
    intro:
      'Halal lamb by the carcass, the leg or the kilo. Choose whole and half lamb for family events, frenched cutlets and loin chops for the grill, or bone-in curry pieces and boneless diced lamb for slow cooking — all certified halal by Halal Control Australia.',
    subcategories: [
      'Whole & Half Carcass',
      'Frenched Cutlets & Loin Chops',
      'Forequarter & Hindquarter',
      'Easy-Carve Leg of Lamb',
      'Lamb Shanks & Shoulders',
      'Bone-in Curry & Biryani Cuts',
      'Boneless Diced & Mince',
    ],
  },
  {
    slug: 'goat',
    name: 'Goat',
    kw: 'halal goat meat',
    tagline: 'Whole goat, curry cut, diced, legs, chops and shanks',
    intro:
      'Halal goat meat for curries, biryani, mandi and roasts. Buy a whole goat carcass, bone-in curry cut in 5kg packs, lean boneless diced goat, or legs, shoulders, cutlets and shanks — certified halal by Halal Control Australia and delivered Australia-wide.',
    subcategories: [
      'Whole Goat Carcass',
      'Bone-in Curry Cut',
      'Boneless Diced Goat',
      'Goat Leg & Shoulder Roasts',
      'Goat Chops & Ribs',
      'Goat Shanks & Stew Pieces',
    ],
  },
  {
    slug: 'chicken',
    name: 'Chicken',
    kw: 'halal chicken',
    tagline: 'Whole birds, fillets, drumsticks, wings and bulk cartons',
    intro:
      'Halal chicken in household packs and commercial cartons: whole birds, skinless breast and thigh fillets, drumsticks, wings, bone-in curry cut and free-range birds. 10kg cartons suit takeaways and caterers. All chicken is certified halal by Halal Control Australia.',
    subcategories: [
      'Whole Broiler & Roasting Birds',
      'Skinless Breast Fillets',
      'Thigh Fillets & Cutlets',
      'Drumsticks & Wings',
      'Bone-in Curry & Biryani Cuts',
      'Corn-Fed & Free-Range Birds',
      'Bulk Commercial Cartons',
    ],
  },
  {
    slug: 'camel',
    name: 'Camel',
    kw: 'halal camel meat',
    tagline: 'Steaks, tomahawk, diced, mince, neck and osso buco',
    intro:
      'Halal camel meat is lean, rich in iron and a staple of Middle Eastern, Somali and North African cooking. Choose portioned porterhouse, scotch fillet, eye fillet and rump steaks, a showpiece camel tomahawk, diced camel and mince, or bone-in neck and osso buco for slow cooking — all frozen and certified halal by Halal Control Australia.',
    subcategories: ['Camel Steaks', 'Camel Tomahawk', 'Diced Camel', 'Camel Mince', 'Neck & Osso Buco'],
  },
  {
    slug: 'duck',
    name: 'Duck',
    kw: 'halal duck',
    tagline: 'Whole ducks, breasts, legs, mince, liver and duck fat',
    intro:
      'Halal duck for roasting, braising and special occasions. Order whole ducks including corn-fed Wimmera Gold, skin-on breast fillets, duck legs for confit, duck mince, livers, rendered duck fat and bones for stock — every pack certified halal by Halal Control Australia.',
    subcategories: ['Whole Ducks', 'Duck Breast', 'Duck Legs', 'Duck Mince', 'Duck Liver', 'Duck Fat & Bones'],
  },
  {
    slug: 'kangaroo',
    name: 'Kangaroo',
    kw: 'halal kangaroo meat',
    tagline: 'Fillets, loin, topside, mince, burgers, sausages and tail',
    intro:
      'Kangaroo is one of the leanest red meats available — high in protein and iron, low in fat. Our halal kangaroo range covers fillets and loin, topside for slow cooking, lean mince, burgers, sausages and tail for slow braising, all certified halal by Halal Control Australia.',
    subcategories: ['Kangaroo Fillets', 'Kangaroo Topside', 'Kangaroo Mince', 'Kangaroo Burgers & Sausages', 'Kangaroo Tail'],
  },
  {
    slug: 'water-buffalo',
    name: 'Water Buffalo',
    kw: 'halal buffalo meat',
    tagline: 'Steaks, tomahawk, asado ribs, diced, mince and osso buco',
    intro:
      'Water buffalo is a lean red meat with a clean, slightly sweet flavour that suits both quick grilling and long braising. Shop porterhouse, scotch fillet, rib eye and T-bone steaks, a buffalo tomahawk, thin-cut asado ribs, diced buffalo, mince and osso buco — all frozen and certified halal by Halal Control Australia.',
    subcategories: ['Buffalo Steaks', 'Buffalo Tomahawk', 'Buffalo Ribs', 'Diced Buffalo', 'Buffalo Mince', 'Buffalo Osso Buco'],
  },
  {
    slug: 'wholesale-cartons',
    name: 'Wholesale Cartons',
    kw: 'wholesale halal meat',
    tagline: 'Cryovac primals, restaurant cartons and catering packs',
    intro:
      'Wholesale halal meat cartons for restaurants, takeaways, caterers and community events. Cryovac beef primals, 20kg lamb and goat curry-cut cartons and 20kg beef mince are priced per carton for trade buyers. For weekly volume pricing, open a wholesale account.',
    subcategories: ['Cryovac Primals', 'Restaurant Bulk Cartons', 'Catering Packs'],
  },
]

// p(category, subcategory, name, packLabel, packKg, perKg, short, desc, extra)
function p(cat, sub, name, unit, kg, perKg, short, desc, extra = {}) {
  const slug = extra.slug || name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  return {
    slug,
    name,
    cat,
    sub,
    unit,
    kg,
    perKg,
    price: Math.round(kg * perKg * 100) / 100,
    short,
    desc,
    badge: extra.badge || null,
    featured: Boolean(extra.featured),
    images: [`${slug}-${IMAGE_VERSION}.webp`],
  }
}

export const PRODUCTS = [
  // ── BEEF ──────────────────────────────────────────────────────────────
  p('beef', 'Primal Cuts & Loins', 'Beef Eye Fillet Whole', 'approx. 2kg whole piece', 2, 52,
    'Whole beef eye fillet (tenderloin) — the most tender cut on the animal, ready to trim into steaks or roast whole.',
    'A whole eye fillet gives you the best value per steak: cut it into medallions, tie the centre for a roast, and use the tail for stir-fry or skewers. Vacuum-sealed whole so you portion it exactly how your kitchen needs.',
    { badge: 'Premium', featured: true }),
  p('beef', 'Primal Cuts & Loins', 'Beef Rump Whole', 'approx. 4kg whole piece', 4, 26,
    'Whole beef rump primal with cap, a flavourful all-rounder for steaks, roasts and grilling.',
    'Rump is the workhorse of steak restaurants — firm, beefy and forgiving on the grill. Separate the cap for picanha-style skewers, slice the centre into rump steaks and dice the trim for kebabs.'),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Scotch Fillet Steaks', '2kg pack', 2, 42,
    'Boneless scotch fillet steaks cut from the rib, well marbled for juicy pan-searing and barbecue.',
    'Scotch fillet carries more intramuscular fat than most steaks, which keeps it juicy at medium and above. Sear hard on a hot pan or grill, rest for five minutes and slice against the grain.',
    { badge: 'Popular', featured: true }),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Rib Eye on the Bone', '2kg pack', 2, 38,
    'Bone-in rib eye steaks — thick, marbled and made for charcoal grilling.',
    'Cooking on the bone protects the meat and adds flavour. These thick-cut rib eyes suit a reverse sear: low heat until 50°C inside, then a fast, very hot finish for the crust.'),
  p('beef', 'Porterhouse & T-Bone', 'Beef Porterhouse Steaks', '2kg pack', 2, 34,
    'Porterhouse (sirloin) steaks with a firm texture and a strip of fat for flavour.',
    'Porterhouse is the classic grill steak — lean through the centre with a fat cap that renders as it cooks. Score the fat, season well and cook to medium-rare for the best texture.'),
  p('beef', 'Porterhouse & T-Bone', 'Beef T-Bone Steaks', '2kg pack', 2, 32,
    'T-bone steaks combining sirloin and a piece of tenderloin on one bone.',
    'Two steaks in one: the sirloin side gives bite and flavour, the smaller fillet side melts. Keep the fillet side away from the hottest part of the grill so both finish together.'),
  p('beef', 'Briskets & Short Ribs', 'Beef Brisket Whole', 'approx. 5kg whole piece', 5, 16,
    'Whole beef brisket with point and flat — for smoking, slow braising and nihari.',
    'Brisket needs time: eight to twelve hours of low smoke, or three to four hours braised, turns the connective tissue into gelatine. Trim the fat cap to about 5mm before cooking.',
    { badge: 'Best Value' }),
  p('beef', 'Briskets & Short Ribs', 'Beef Short Ribs', '2kg pack', 2, 22,
    'Meaty beef short ribs for braising, smoking and Korean-style grilling.',
    'Short ribs are rich and generously marbled. Braise them in stock and spices until the meat pulls from the bone, or smoke them low and slow as a weekend centrepiece.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Premium Beef Mince', '5kg pack', 5, 15.5,
    'Premium beef mince in a 5kg pack — for kofta, burgers, pasta sauces and keema.',
    'A lean-to-fat balance that holds together for kofta and burgers without drying out. The 5kg pack is portioned for freezing, so it suits both busy households and small takeaways.',
    { badge: 'Popular', featured: true }),
  p('beef', 'Mince, Diced & Stir-Fry', 'Diced Beef Boneless', '3kg pack', 3, 21,
    'Boneless diced beef cut into even pieces for curries, stews and casseroles.',
    'Even-sized cubes cook at the same rate, so every piece is tender at the same time. Brown in batches for the deepest flavour before adding liquid.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Beef Stir-Fry Strips', '2kg pack', 2, 23,
    'Thin beef strips sliced across the grain for fast stir-fries, fajitas and shawarma-style wraps.',
    'Sliced thin and across the grain so the strips stay tender after a quick, hot cook. Marinate for 30 minutes, then cook in small batches so the pan stays hot.'),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Scotch Fillet MB8-9', '1kg pack', 1, 95,
    'Wagyu scotch fillet with marble score 8–9 — intensely marbled for special occasions.',
    'At marble score 8–9 the fat is spread through the muscle in fine flecks, giving a buttery texture. Cut thinner steaks (about 2cm), sear briefly and serve in small portions.',
    { badge: 'Premium', featured: true }),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Brisket MB9+', 'approx. 5kg whole piece', 5, 34,
    'Marble score 9+ Wagyu brisket — the richest brisket for smoking and braising.',
    'High marbling keeps Wagyu brisket moist through a long smoke. It renders more fat than standard brisket, so trim the cap a little more and wrap once the bark has set.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Osso Buco', '3kg pack', 3, 14.5,
    'Cross-cut beef shin with marrow bone for osso buco, stews and paya-style broths.',
    'The marrow melts into the sauce and the shin meat turns silky after two to three hours of gentle braising. Tie each piece with string to keep it neat in the pot.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Oxtail', '2kg pack', 2, 24,
    'Beef oxtail pieces for rich soups, stews and slow-cooked curries.',
    'Oxtail is mostly bone and collagen, which gives soups and stews a deep, glossy body. Brown well, then simmer for three hours or pressure-cook for about 50 minutes.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Soup Bones', '5kg pack', 5, 5.5,
    'Beef marrow and knuckle bones for stock, broth and soup.',
    'Roast the bones at 220°C until browned, then simmer with onion and spices for six hours or more for a clear, full-bodied stock that freezes well.'),
  p('beef', 'Primal Cuts & Loins', 'Beef Striploin Whole', 'approx. 4.5kg whole piece', 4.5, 30,
    'Whole beef striploin (sirloin) — cut your own porterhouse steaks or roast it whole.',
    'Buying the striploin whole is the cheapest way to get porterhouse-quality steaks. Trim the fat cap to your liking and portion into 2–3cm steaks, or roast whole at 200°C for a sliceable centrepiece.'),
  p('beef', 'Primal Cuts & Loins', 'Beef Topside Whole', 'approx. 6kg whole piece', 6, 17,
    'Lean whole beef topside for roasts, schnitzel, shawarma and thin-sliced stir-fry.',
    'Topside is lean with a tight grain, so it slices cleanly for beef shawarma, schnitzel and minute steaks. Roast it whole to medium-rare and carve thinly against the grain.'),
  p('beef', 'Primal Cuts & Loins', 'Beef Rump Cap (Picanha)', 'approx. 1.5kg whole piece', 1.5, 27,
    'Beef rump cap with its fat cap on — the cut used for picanha skewers and churrasco.',
    'Slice into thick steaks with the grain, fold each one into a C-shape and skewer with the fat on the outside. Grill over hot coals so the fat renders and bastes the meat.'),
  p('beef', 'Primal Cuts & Loins', 'Beef Eye Fillet Medallions', '1kg pack', 1, 54,
    'Ready-cut beef eye fillet medallions — the most tender steak, trimmed and portioned.',
    'Fully trimmed and cut into even medallions, so there is no waste and no knife work. Sear for two to three minutes a side and rest before serving.',
    { badge: 'Premium' }),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Tomahawk Steaks', '2 steaks, approx. 2.4kg', 2.4, 39,
    'Thick-cut tomahawk rib eye steaks with the long rib bone — a showpiece for the grill.',
    'Each tomahawk weighs around 1.2kg and feeds two to three people. Reverse-sear it: cook gently until 50°C in the centre, then finish over very high heat for the crust.',
    { badge: 'Premium' }),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Scotch Fillet Whole', 'approx. 4kg whole piece', 4, 36,
    'Whole boneless scotch fillet (cube roll) for cutting your own steaks or slow roasting.',
    'The best value way to buy scotch fillet. Cut thick steaks for the grill, or roast whole at 180°C and slice thinly for a well-marbled roast beef.'),
  p('beef', 'Porterhouse & T-Bone', 'Beef Sirloin Steaks Boneless', '3kg bulk pack', 3, 31,
    'Bulk pack of boneless sirloin steaks, trimmed and cut to an even thickness.',
    'A freezer-friendly bulk pack of sirloin steaks at a lower per-kilo price than our 2kg pack. Each steak is cut to the same thickness so a whole tray cooks evenly.'),
  p('beef', 'Briskets & Short Ribs', 'Beef Brisket Bone-in Curry Cut', '3kg pack', 3, 15.5,
    'Bone-in beef brisket cut into curry pieces — the classic cut for nihari and slow stews.',
    'The bone and fat in brisket break down into a rich, glossy gravy. Simmer gently for three hours, or about one hour in a pressure cooker, for nihari, haleem and paya-style stews.'),
  p('beef', 'Briskets & Short Ribs', 'Beef Plate Short Ribs', 'approx. 3kg rack', 3, 24,
    'A rack of beef plate short ribs — the large, meaty "dino" ribs for smoking.',
    'These are the big ribs from the plate, each carrying a thick layer of meat. Smoke at 120°C for eight hours or more until they probe tender, or braise them whole.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Lean Beef Mince', '3kg pack', 3, 19.5,
    'Low-fat beef mince for health-conscious cooking, pasta sauces and lean kofta.',
    'Made from trimmed lean cuts, so very little fat renders out in the pan. Ideal for bolognese, keema and stuffed vegetables.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Beef Kofta Mince', '2kg pack', 2, 17,
    'Finely minced beef with the right fat ratio for kofta, kafta and kebab skewers.',
    'Minced fine so it binds tightly on skewers. Mix with grated onion, parsley and seven spice, press onto skewers and grill over high heat.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Beef Minute Steaks', '2kg pack', 2, 22,
    'Thin-sliced beef minute steaks for quick pan-frying, sandwiches and schnitzel.',
    'Cut thin so they cook in about a minute a side. Crumb them for schnitzel, or season and sear hot for steak sandwiches and wraps.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Beef Chuck Steak', '3kg pack', 3, 21,
    'Beef chuck steak — a well-marbled cut for dicing into stews, curries and pies.',
    'Chuck has plenty of connective tissue that melts into tender, flavourful meat after two to three hours of slow cooking. Dice it yourself for stews and pies.'),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Tomahawk MB9+', 'approx. 1.5kg steak', 1.5, 145,
    'Marble score 9+ Wagyu tomahawk — one of the most heavily marbled steaks available.',
    'At MB9+ the steak is laced with fine marbling, so it needs less cooking than standard beef. Sear hard, rest well and slice thinly to share.',
    { badge: 'Premium' }),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Topside MB8-9', 'approx. 2kg piece', 2, 35,
    'Wagyu topside at marble score 8–9 — a richly marbled roast and thin-slicing cut.',
    'Wagyu marbling turns a normally lean topside into a juicy roast. Roast to medium-rare, or slice paper-thin for hot pot, shabu-shabu and stir-fries.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Shin Boneless', '2kg pack', 2, 19,
    'Boneless beef shin for slow braises, curries and nihari.',
    'Shin is threaded with connective tissue that turns silky after a long, slow cook. It holds its shape in curries and stews better than any other diced cut.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Marrow Bones Cut', '3kg pack', 3, 8,
    'Beef marrow bones cut into short lengths for roasting, broth and paya-style soups.',
    'Roast at 220°C for 20 minutes and spread the marrow on toast, or simmer for hours for a rich, gelatinous broth.'),

  // ── LAMB ──────────────────────────────────────────────────────────────
  p('lamb', 'Whole & Half Carcass', 'Whole Lamb Carcass', 'approx. 20kg carcass', 20, 16.5,
    'A whole lamb carcass, cut to your instructions — ideal for family events and gatherings.',
    'Order a whole lamb and tell us how you want it cut: curry pieces, roasts, chops, or a mix. Add your cutting instructions in the order notes at checkout.',
    { badge: 'Best Value', featured: true }),
  p('lamb', 'Whole & Half Carcass', 'Half Lamb Carcass', 'approx. 10kg half carcass', 10, 17,
    'Half a lamb carcass, cut to your instructions — a full mix of roasts, chops and curry cuts.',
    'A practical way to stock the freezer: half a lamb typically yields a leg, a shoulder, chops, shanks and a good quantity of curry pieces. Specify your cuts in the order notes.'),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Cutlets Frenched', '1kg pack', 1, 46,
    'Frenched lamb cutlets with the rib bone cleaned — elegant, tender and quick to cook.',
    'Cutlets need only two to three minutes a side on a hot grill. Season simply with salt, garlic and rosemary, or marinate in yoghurt and spices for a tandoori-style finish.',
    { badge: 'Premium' }),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Loin Chops', '2kg pack', 2, 30,
    'Lamb loin chops — tender, meaty and perfect for the barbecue.',
    'Loin chops have a small T-shaped bone with tender loin on one side. Grill over high heat and rest briefly; they are at their best pink in the middle.'),
  p('lamb', 'Forequarter & Hindquarter', 'Lamb Forequarter Chops', '3kg pack', 3, 17,
    'Lamb forequarter chops — flavourful, budget-friendly chops for grilling and braising.',
    'Forequarter chops have more connective tissue than loin chops, which means more flavour. Grill them hot and fast, or braise in a tomato and spice sauce until tender.'),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Leg Bone-in', 'approx. 2.5kg whole leg', 2.5, 19,
    'Whole bone-in leg of lamb for roasting, raan and slow cooking.',
    'Stud the leg with garlic, rub with spices and roast at 180°C — allow about 25 minutes per kilo for pink, or slow-roast for five hours until it falls from the bone.',
    { featured: true }),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Leg Boneless', 'approx. 2kg rolled leg', 2, 24,
    'Boneless leg of lamb, rolled and netted for easy carving.',
    'With the bone removed the leg cooks evenly and carves into neat slices. Unroll it to stuff with herbs and garlic, or butterfly it flat for the barbecue.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shanks', '2kg pack', 2, 20,
    'Lamb shanks for slow braising — tender, gelatinous and full of flavour.',
    'Braise shanks for two and a half to three hours in a covered pot until the meat slides off the bone. They reheat beautifully, so cook a big batch.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shoulder Bone-in', 'approx. 2.5kg whole shoulder', 2.5, 16,
    'Bone-in lamb shoulder for slow roasting, shawarma and pulled lamb.',
    'Shoulder has more fat and connective tissue than the leg, which makes it ideal for long, slow cooking. Roast covered at 150°C for four to five hours and pull apart with forks.'),
  p('lamb', 'Bone-in Curry & Biryani Cuts', 'Lamb Curry Pieces', '5kg pack', 5, 13.5,
    'Bone-in lamb curry pieces, cut through the bone for curries, biryani and mansaf.',
    'Cutting through the bone releases marrow and collagen into the sauce, giving curries more body. Pieces are cut to a consistent size so they cook evenly.',
    { badge: 'Popular', featured: true }),
  p('lamb', 'Boneless Diced & Mince', 'Diced Lamb Boneless', '3kg pack', 3, 27,
    'Boneless diced lamb for kebabs, curries and stews.',
    'Trimmed and cut into even cubes. For skewers, marinate overnight in yoghurt, lemon and spices; for curries, brown well before adding the sauce.'),
  p('lamb', 'Boneless Diced & Mince', 'Lamb Mince', '3kg pack', 3, 16,
    'Lamb mince for kofta, kibbeh, keema and meatballs.',
    'Lamb mince carries more flavour than beef and suits warm spices. Mix with onion, parsley and allspice for kofta, or brown with garam masala for keema.'),
  p('lamb', 'Whole & Half Carcass', 'Whole Mutton Carcass', 'approx. 25kg carcass', 25, 11.5,
    'A whole mutton carcass, cut to your instructions — deeper flavour for curries and slow cooking.',
    'Mutton comes from older sheep and has a stronger, richer flavour than lamb that stands up to long-cooked curries, biryani and haleem. Add your cutting instructions in the order notes.',
    { badge: 'Best Value' }),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Rack Frenched', '1kg pack', 1, 38,
    'Whole frenched lamb racks, about 8 cutlets each, for roasting or cutting into cutlets.',
    'Roast whole at 200°C for about 20 minutes for pink meat, rest, then carve between the bones. A crust of herbs, garlic and mustard works well.'),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Backstrap', '1kg pack', 1, 45,
    'Lamb backstrap (loin eye) — lean, boneless and very tender.',
    'Backstrap is the eye of the loin with all fat and sinew removed. Sear for three minutes a side, rest for five and slice into medallions.',
    { badge: 'Premium' }),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Chump Chops', '2kg pack', 2, 21,
    'Lamb chump chops from the rump end of the loin — meaty and great on the barbecue.',
    'Chump chops are thicker and meatier than loin chops at a lower price. Grill over medium-high heat and rest briefly.'),
  p('lamb', 'Forequarter & Hindquarter', 'Lamb Forequarter Whole', 'approx. 5kg piece', 5, 14,
    'A whole lamb forequarter (shoulder, neck and ribs), cut to your instructions.',
    'The forequarter is the most flavourful part of the lamb and the best value. Have it cut into curry pieces, chops and a shoulder roast — add your instructions in the order notes.'),
  p('lamb', 'Forequarter & Hindquarter', 'Lamb Hindquarter Whole', 'approx. 7kg piece', 7, 17.5,
    'A whole lamb hindquarter (legs and loin), cut to your instructions.',
    'The hindquarter gives you both legs and the loin. Ask for a leg roast, loin chops and curry pieces, or leave it whole for a large gathering.'),
  p('lamb', 'Forequarter & Hindquarter', 'Lamb Neck Chops', '2kg pack', 2, 16,
    'Lamb neck chops for curries, stews and slow braises.',
    'Neck is full of flavour and collagen, so it becomes soft and rich after a long, slow cook. A favourite cut for Afghan and Pakistani-style curries.'),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Easy-Carve Leg', 'approx. 2kg leg', 2, 21,
    'Easy-carve leg of lamb with the hip bone removed, so it carves cleanly at the table.',
    'With the awkward hip bone taken out, the leg roasts evenly and slices neatly. Roast at 180°C for about 25 minutes per kilo for pink meat.'),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Leg Butterflied', 'approx. 1.8kg piece', 1.8, 26,
    'Boneless leg of lamb opened flat for marinating and grilling.',
    'Butterflied leg cooks in about 30 minutes on a hot barbecue. Marinate overnight in yoghurt, garlic and spices, grill and rest before slicing.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shoulder Boneless Rolled', 'approx. 2kg rolled piece', 2, 22,
    'Boneless lamb shoulder, rolled and netted, for slow roasting and shawarma.',
    'With the bone removed the shoulder cooks evenly and slices neatly. Roast low and slow, or slice thinly for homemade lamb shawarma.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shanks Frenched', '2kg pack', 2, 22,
    'Frenched lamb shanks with the bone tip cleaned — a restaurant-style braise.',
    'The trimmed bone looks neat on the plate. Braise for two and a half hours until the meat is meltingly soft.'),
  p('lamb', 'Bone-in Curry & Biryani Cuts', 'Lamb Mansaf Pieces', '5kg pack', 5, 17,
    'Large bone-in lamb pieces cut for mansaf, kabsa and mandi.',
    'Bigger than curry pieces, so the meat stays succulent through long cooking and looks generous on a shared platter.'),
  p('lamb', 'Bone-in Curry & Biryani Cuts', 'Lamb Biryani Cut Leg & Shoulder', '3kg pack', 3, 17,
    'Bone-in lamb biryani cut from the leg and shoulder — meatier pieces with less bone.',
    'Taken from the meatiest parts of the lamb, so every piece in the pot is substantial. Marinate overnight before layering with rice.'),
  p('lamb', 'Boneless Diced & Mince', 'Lamb Kofta Mince', '2kg pack', 2, 20,
    'Finely minced lamb for kofta, kafta and kibbeh.',
    'Minced fine so it binds well on skewers and in kibbeh. Season with onion, parsley and spice, and grill over high heat.'),

  // ── GOAT ──────────────────────────────────────────────────────────────
  p('goat', 'Whole Goat Carcass', 'Whole Goat Carcass', 'approx. 12kg carcass', 12, 17.5,
    'A whole young goat carcass, cut to your instructions for curries, roasts and events.',
    'A whole goat is the most economical way to buy for large gatherings. Tell us your preferred cuts — curry pieces, legs, shoulders, chops — in the order notes.',
    { badge: 'Best Value', featured: true }),
  p('goat', 'Bone-in Curry Cut', 'Goat Curry Cut Bone-in', '5kg pack', 5, 16.5,
    'Bone-in goat curry cut — the classic choice for curries, biryani, karahi and mandi.',
    'Mixed pieces from across the carcass, cut through the bone for rich, full-bodied curries. Allow about 90 minutes of gentle simmering, or 30 minutes in a pressure cooker.',
    { badge: 'Popular', featured: true }),
  p('goat', 'Boneless Diced Goat', 'Diced Goat Boneless', '3kg pack', 3, 27,
    'Lean boneless diced goat for stews, curries and skewers.',
    'All the flavour of goat without the bones. Goat is lean, so cook it gently — slow simmering or a long marinade before grilling keeps it tender.'),
  p('goat', 'Goat Leg & Shoulder Roasts', 'Goat Leg Bone-in', 'approx. 2kg whole leg', 2, 24,
    'Bone-in goat leg for slow roasting and festive dishes.',
    'Marinate overnight in yoghurt, garlic and spices, then roast covered at 160°C for three hours. The meat should pull easily from the bone.'),
  p('goat', 'Goat Leg & Shoulder Roasts', 'Goat Shoulder Bone-in', 'approx. 2kg whole shoulder', 2, 21,
    'Bone-in goat shoulder for slow-cooked roasts and pulled goat.',
    'The shoulder has more marbling than the leg and stays succulent through long cooking. Ideal for mandi-style slow roasting.'),
  p('goat', 'Goat Chops & Ribs', 'Goat Cutlets and Chops', '2kg pack', 2, 33,
    'Goat cutlets and chops for grilling and pan-frying.',
    'Tender chops from the rack and loin. Marinate for a few hours and grill over medium-high heat — goat is lean, so avoid overcooking.'),
  p('goat', 'Goat Chops & Ribs', 'Goat Ribs', '2kg pack', 2, 18,
    'Goat ribs for slow grilling, braising and soups.',
    'Ribs carry a good amount of fat for goat, so they crisp nicely after a slow cook. Braise until tender, then finish on a hot grill.'),
  p('goat', 'Goat Shanks & Stew Pieces', 'Goat Shanks and Stew Pieces', '3kg pack', 3, 17,
    'Goat shanks and stew pieces for slow-cooked soups and stews.',
    'Collagen-rich pieces that turn soft and sticky after two hours of slow cooking. A great base for paya, nihari-style stews and hearty soups.'),
  p('goat', 'Whole Goat Carcass', 'Half Goat Carcass', 'approx. 6kg half carcass', 6, 18.5,
    'Half a goat carcass, cut to your instructions — a good size for a family or small gathering.',
    'Half a goat gives you a leg, a shoulder, chops and a good quantity of curry pieces. Add your preferred cuts in the order notes.'),
  p('goat', 'Bone-in Curry Cut', 'Goat Mandi Pieces', '5kg pack', 5, 17,
    'Large bone-in goat pieces cut for mandi, kabsa and slow roasting.',
    'Bigger pieces from the leg and shoulder that stay juicy under long, slow cooking. Season well and cook over rice or in a covered roasting pan.'),
  p('goat', 'Boneless Diced Goat', 'Goat Mince', '2kg pack', 2, 20,
    'Goat mince for keema, kofta and stuffed vegetables.',
    'Goat mince is lean with a clean, rich flavour. Brown with onion, ginger and garam masala for keema, or mix with herbs for kofta.'),
  p('goat', 'Goat Leg & Shoulder Roasts', 'Goat Leg Boneless', 'approx. 1.5kg piece', 1.5, 30,
    'Boneless goat leg for roasting, butterflying and dicing.',
    'With the bone removed the leg cooks evenly. Butterfly it for the grill, roll it for roasting, or dice it for kebabs.'),
  p('goat', 'Goat Chops & Ribs', 'Goat Neck Chops', '2kg pack', 2, 16,
    'Goat neck chops for curries and slow-cooked stews.',
    'Neck is the most flavourful part of the goat and cooks down into a rich, thick sauce. Simmer gently for two hours or pressure-cook for 35 minutes.'),

  // ── CHICKEN ───────────────────────────────────────────────────────────
  p('chicken', 'Whole Broiler & Roasting Birds', 'Whole Chickens Size 16', '10 birds, approx. 16kg', 16, 7,
    'Ten whole chickens (size 16, about 1.6kg each) for roasting, charcoal chicken and curries.',
    'A carton of ten size-16 birds suits large families, charcoal chicken shops and caterers. Roast at 200°C for about 75 minutes, or butterfly for the grill.',
    { badge: 'Best Value', featured: true }),
  p('chicken', 'Skinless Breast Fillets', 'Chicken Breast Fillets', '5kg pack', 5, 12.5,
    'Skinless chicken breast fillets for grilling, schnitzel, stir-fries and wraps.',
    'Lean and versatile. Butterfly or pound thick fillets to an even thickness so they cook through without drying out.',
    { badge: 'Popular', featured: true }),
  p('chicken', 'Thigh Fillets & Cutlets', 'Chicken Thigh Fillets', '5kg pack', 5, 14,
    'Boneless, skinless chicken thigh fillets — juicy and forgiving for shish, curries and shawarma.',
    'Thigh fillets stay moist even when cooked over high heat, which is why most kebab and shawarma kitchens prefer them to breast.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Drumsticks', '5kg pack', 5, 5.5,
    'Chicken drumsticks for roasting, frying and the barbecue.',
    'Economical and family-friendly. Score the meat and marinate overnight, then bake at 200°C for 40 minutes or grill over medium heat.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Wings', '5kg pack', 5, 5,
    'Whole chicken wings for frying, baking and grilling.',
    'Pat dry and bake on a rack at 220°C for crisp skin, or fry and toss in sauce. Separate into drumettes and wingettes if you prefer.'),
  p('chicken', 'Bone-in Curry & Biryani Cuts', 'Chicken Curry Cut Bone-in', '5kg pack', 5, 9,
    'Skinless bone-in chicken curry cut for curries, biryani and karahi.',
    'Whole birds cut into curry-sized pieces with the skin removed, so the masala reaches the meat. Ready to cook straight from the pack.'),
  p('chicken', 'Corn-Fed & Free-Range Birds', 'Free-Range Whole Chickens', '4 birds, approx. 7.2kg', 7.2, 10.5,
    'Four free-range whole chickens (about 1.8kg each) for roasting.',
    'Free-range birds have a firmer texture and fuller flavour. Roast whole with lemon and garlic, or spatchcock for faster, even cooking.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Breast Fillet Carton', '10kg carton', 10, 11.5,
    'A 10kg carton of skinless chicken breast fillets for takeaways and caterers.',
    'Commercial carton pricing for kitchens that go through breast fillet every day. Fillets are packed in bags inside the carton for easier portioning.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Thigh Fillet Carton', '10kg carton', 10, 13,
    'A 10kg carton of boneless chicken thigh fillets for shawarma, shish and grills.',
    'The go-to cut for shawarma cones and charcoal skewers, at carton pricing. Ideal for restaurants that marinate in bulk.'),
  p('chicken', 'Whole Broiler & Roasting Birds', 'Whole Chickens Size 12', '10 birds, approx. 12kg', 12, 7.5,
    'Ten whole chickens (size 12, about 1.2kg each) — smaller birds for charcoal chicken and family meals.',
    'Size 12 birds cook faster and portion neatly into halves and quarters, which is why charcoal chicken shops prefer them. Butterfly and grill, or roast whole.'),
  p('chicken', 'Whole Broiler & Roasting Birds', 'Chicken Spatchcocks', '6 birds, approx. 3kg', 3, 14,
    'Six young spatchcocks (poussin) — one bird per person for grilling and roasting.',
    'Small, tender birds that cook in about 30 minutes. Split down the backbone, flatten and grill with a lemon and garlic marinade.'),
  p('chicken', 'Skinless Breast Fillets', 'Chicken Tenderloins', '5kg pack', 5, 13.5,
    'Chicken breast tenderloins — the tenderest strip of the breast, for skewers, strips and nuggets.',
    'Tenderloins are naturally portion-sized, so there is no cutting. Crumb them for tenders, thread onto skewers or pan-fry for wraps.'),
  p('chicken', 'Skinless Breast Fillets', 'Chicken Schnitzel Slices', '3kg pack', 3, 14.5,
    'Chicken breast sliced thin and even, ready to crumb for schnitzel.',
    'Each fillet is butterflied and sliced to an even thickness so it cooks through quickly without drying out. Crumb and shallow-fry for three minutes a side.'),
  p('chicken', 'Thigh Fillets & Cutlets', 'Chicken Thigh Cutlets Bone-in', '5kg pack', 5, 9,
    'Bone-in, skin-on chicken thigh cutlets for roasting, grilling and curries.',
    'The bone keeps thigh cutlets juicy and adds flavour. Roast at 200°C for 35–40 minutes for crisp skin.'),
  p('chicken', 'Thigh Fillets & Cutlets', 'Chicken Maryland', '5kg pack', 5, 8.5,
    'Chicken maryland — the whole leg with thigh and drumstick attached.',
    'An economical, generous portion. Marinate and bake at 200°C for about 45 minutes, or grill over medium coals, turning often.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Wingettes and Drumettes', '5kg pack', 5, 7.5,
    'Chicken wings split into wingettes and drumettes, ready for frying, baking and sauces.',
    'Pre-cut with the tips removed, so they are ready for the fryer or oven. Toss in sauce straight after cooking.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Drumsticks Skinless', '5kg pack', 5, 7,
    'Skinless chicken drumsticks — the marinade goes straight into the meat.',
    'With the skin removed, tandoori and tikka marinades penetrate deeper. Score the meat, marinate overnight and roast or grill.'),
  p('chicken', 'Corn-Fed & Free-Range Birds', 'Corn-Fed Whole Chickens', '4 birds, approx. 6.4kg', 6.4, 11,
    'Four corn-fed whole chickens (about 1.6kg each) with golden skin and rich flavour.',
    'A corn-based diet gives these birds their yellow skin and a richer flavour. Roast whole or spatchcock for the grill.'),
  p('chicken', 'Corn-Fed & Free-Range Birds', 'Free-Range Chicken Breast Fillets', '3kg pack', 3, 15,
    'Skinless free-range chicken breast fillets for grilling, schnitzel and salads.',
    'Free-range breast has a firmer texture and fuller flavour. Brine briefly or marinate to keep it juicy on the grill.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Drumstick Carton', '15kg carton', 15, 5,
    'A 15kg carton of chicken drumsticks for takeaways, caterers and large families.',
    'Our lowest per-kilo price on drumsticks, packed in bags inside the carton for easier freezing and portioning.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Wing Carton', '15kg carton', 15, 4.8,
    'A 15kg carton of whole chicken wings for wing bars, takeaways and events.',
    'Carton pricing for kitchens that go through wings every day. Split into wingettes and drumettes or cook whole.'),

  // ── CAMEL ─────────────────────────────────────────────────────────────
  // All camel is sold frozen.
  p('camel', 'Camel Steaks', 'Camel Porterhouse Steaks', '2 x 300g steaks, frozen', 0.6, 50,
    'Two boneless camel porterhouse steaks — lean, tender and portioned for the grill.',
    'Camel porterhouse is very lean, so cook it fast and hot. Thaw overnight in the fridge, oil and season the steaks, sear to medium-rare and rest for five minutes before slicing.',
    { featured: true }),
  p('camel', 'Camel Steaks', 'Camel Porterhouse on the Bone', '2 x 300g steaks, frozen', 0.6, 50,
    'Two bone-in camel porterhouse steaks — the bone adds flavour and protects the lean meat.',
    'Cooking on the bone helps keep lean camel juicy. Grill over high heat to medium-rare and rest well before serving.'),
  p('camel', 'Camel Steaks', 'Camel Scotch Fillet Steaks', '2 x 300g steaks, frozen', 0.6, 50,
    'Two camel scotch fillet steaks — the most marbled of the camel steaks.',
    'Scotch fillet carries a little more fat than other camel cuts, which makes it the most forgiving steak to cook. Sear hard and serve medium-rare.'),
  p('camel', 'Camel Steaks', 'Camel Eye Fillet Steaks', '2 x 200g steaks, frozen', 0.4, 70,
    'Two camel eye fillet steaks — the tenderest cut on the camel.',
    'Eye fillet needs only two to three minutes a side in a very hot pan. Rest for five minutes, then slice into thick medallions.',
    { badge: 'Premium' }),
  p('camel', 'Camel Steaks', 'Camel Rump Steaks', '2 x 250g steaks, frozen', 0.5, 30,
    'Two camel rump steaks — firm, flavourful and great value.',
    'Rump has more bite and flavour than the loin cuts. Marinate in oil, garlic and spice, sear hot, rest and slice thinly against the grain.',
    { badge: 'Best Value' }),
  p('camel', 'Camel Tomahawk', 'Camel Tomahawk', '1 steak, approx. 800g, frozen', 0.8, 87.5,
    'A bone-in camel tomahawk steak — a striking centrepiece for the barbecue.',
    'Reverse-sear it: cook gently until 50°C in the centre, then finish over very high heat for a crust. Rest for ten minutes and carve off the bone to share.',
    { badge: 'Premium' }),
  p('camel', 'Diced Camel', 'Diced Camel Boneless', '2kg pack, frozen', 2, 20,
    'Boneless diced camel for stews, curries, kabsa and suqaar.',
    'Lean, trimmed cubes ready for the pot. Simmer gently for two to three hours for stews, or cut smaller and stir-fry with onion, capsicum and spices for Somali-style suqaar.'),
  p('camel', 'Camel Mince', 'Camel Mince', '2kg pack, frozen', 2, 16.5,
    'Lean camel mince for burgers, kofta and stuffed vegetables.',
    'Very lean mince with a mild, slightly sweet flavour. Add grated onion or a little oil to keep burgers and kofta moist.'),
  p('camel', 'Neck & Osso Buco', 'Camel Neck Disc Bone-in', '2kg pack, frozen', 2, 17.5,
    'Bone-in camel neck discs for slow-cooked stews, soups and mandi.',
    'Neck is rich in collagen and turns soft and sticky after a long, slow cook. Braise for three hours or pressure-cook for about 50 minutes.'),
  p('camel', 'Neck & Osso Buco', 'Camel Osso Buco', '1kg pack, frozen', 1, 20,
    'Cross-cut camel shin with marrow bone for slow braises and soups.',
    'The marrow melts into the sauce as it cooks. Braise gently for three hours with tomato, onion and warm spices until the meat is soft.'),

  // ── DUCK ──────────────────────────────────────────────────────────────
  p('duck', 'Whole Ducks', 'Whole Duck Size 20-23', '1 bird, approx. 2.2kg', 2.2, 10.71,
    'A whole duck, size 20 to 23 (about 2.0–2.3kg), for roasting and braising.',
    'Prick the skin, season generously and roast at 180°C for about two hours, pouring off the fat as it renders. Save the fat — it makes exceptional roast potatoes.',
    { featured: true, badge: 'Best Value' }),
  p('duck', 'Whole Ducks', 'Whole Wimmera Gold Duck Corn-Fed', '1 bird, approx. 2.2kg', 2.2, 16.8,
    'A whole corn-fed Wimmera Gold duck with golden skin and rich, full flavour.',
    'A corn-based diet gives these ducks their golden skin and a richer flavour. Dry the skin overnight in the fridge, then roast at 180°C for about two hours for crisp skin.',
    { badge: 'Premium' }),
  p('duck', 'Duck Breast', 'Duck Breast Fillets', '4 breasts, approx. 1.2kg', 1.2, 34.76,
    'Four skin-on duck breast fillets — score, render and serve pink.',
    'Start skin-side down in a cold pan and cook gently for eight to ten minutes to render the fat, then turn for two minutes. Rest and slice.'),
  p('duck', 'Duck Legs', 'Duck Legs', '1kg pack', 1, 23.96,
    'Duck legs (thigh and drumstick) for confit, braising and roasting.',
    'The leg is the most forgiving part of the duck. Slow-cook in its own fat for confit, or braise with orange and spices until the meat falls away.'),
  p('duck', 'Duck Mince', 'Duck Mince', '2kg pack', 2, 20.76,
    'Minced duck meat for burgers, meatballs, dumplings and larb.',
    'Rich and full-flavoured. Season with ginger, garlic and spring onion for dumplings and meatballs, or stir-fry with chilli and herbs for larb.'),
  p('duck', 'Duck Liver', 'Duck Livers', '2kg pack', 2, 9.68,
    'Duck livers for pâté, pan-frying and traditional dishes.',
    'Rich and creamy. Pan-fry briefly with onion and spices until just pink inside, or blend into a smooth pâté.'),
  p('duck', 'Duck Fat & Bones', 'Rendered Duck Fat', '2 litre tub', 1.8, 28.2333,
    'Two litres of rendered duck fat for roasting potatoes, confit and frying.',
    'Duck fat has a high smoke point and a rich flavour. Use it to roast potatoes and vegetables, to confit duck legs, or anywhere you would use oil or ghee.'),
  p('duck', 'Duck Fat & Bones', 'Duck Bones Carton', '15kg carton', 15, 5.81,
    'A 15kg carton of duck bones for stock, broth and soup.',
    'Roast the bones until browned, then simmer for four to six hours for a rich, clear duck stock. Ideal for restaurants making stock in bulk.',
    { badge: 'Trade' }),

  // ── KANGAROO ──────────────────────────────────────────────────────────
  p('kangaroo', 'Kangaroo Fillets', 'Kangaroo Fillets', 'approx. 250g pack', 0.25, 36,
    'Lean, tender kangaroo fillets — a very lean red meat for searing and grilling.',
    'With under 2% fat, kangaroo fillet must be cooked quickly: sear for two to three minutes a side to rare or medium-rare and rest well before slicing.',
    { featured: true }),
  p('kangaroo', 'Kangaroo Fillets', 'Kangaroo Loin Fillet', 'approx. 1kg pack', 1, 27,
    'Kangaroo loin fillet for baking, pan-frying and grilling.',
    'The loin is the most tender kangaroo cut. Oil the meat rather than the pan, sear hot and stop at medium-rare — overcooking is the only way to make kangaroo tough.',
    { badge: 'Best Value' }),
  p('kangaroo', 'Kangaroo Fillets', 'Kangaroo Loin Fillets 500g Pack', 'approx. 500g pack', 0.5, 30,
    'A half-kilo pack of plain kangaroo loin fillets — ready for the grill.',
    'A smaller pack for a family meal. Season simply, grill over high heat for two to three minutes a side and rest before slicing.'),
  p('kangaroo', 'Kangaroo Topside', 'Kangaroo Topside', 'approx. 1kg piece', 1, 26,
    'Lean kangaroo topside for slow-cooked casseroles, stews and curries.',
    'Dice it for stews and curries and keep the heat low — kangaroo becomes tender after about 90 minutes of gentle simmering.'),
  p('kangaroo', 'Kangaroo Mince', 'Kangaroo Mince', '1kg pack', 1, 24,
    'Lean kangaroo mince for meatballs, burgers, bolognese and kofta.',
    'One of the leanest minces available. Add a little oil or finely grated vegetables to burgers and meatballs to keep them moist.'),
  p('kangaroo', 'Kangaroo Burgers & Sausages', 'Kangaroo Burgers', '6 burgers, approx. 540g', 0.54, 24.0741,
    'Six kangaroo burgers with basil and sun-dried tomato — gluten free, no preservatives.',
    'Grill or pan-fry over medium heat for four to five minutes a side. Or break them into meatballs and simmer in passata for an Aussie twist on spaghetti and meatballs.'),
  p('kangaroo', 'Kangaroo Burgers & Sausages', 'Kangaroo Sausages', 'approx. 500g pack', 0.5, 28,
    'Lean kangaroo sausages for the barbecue and quick weeknight dinners.',
    'Kangaroo sausages are leaner than most, so cook them over medium heat, turning often, and do not prick them so they stay juicy.'),
  p('kangaroo', 'Kangaroo Tail', 'Kangaroo Tail', 'each, approx. 1kg', 1, 19,
    'A meaty, gelatinous kangaroo tail for soups and slow braises.',
    'Like oxtail, kangaroo tail is rich in collagen. Braise for three hours or more for a deeply flavoured, glossy stew or soup.'),

  // ── WATER BUFFALO ─────────────────────────────────────────────────────
  // All buffalo is sold frozen.
  p('water-buffalo', 'Buffalo Steaks', 'Buffalo Porterhouse Steaks', '2 x 200g steaks, frozen', 0.4, 66.25,
    'Two water buffalo porterhouse steaks — lean, tender and slightly sweet.',
    'Buffalo has less fat than beef, so it cooks faster. Thaw overnight in the fridge, grill to medium-rare over high heat and rest for five minutes.',
    { featured: true }),
  p('water-buffalo', 'Buffalo Steaks', 'Buffalo Scotch Fillet Steaks', '2 x 300g steaks, frozen', 0.6, 53.33,
    'Two water buffalo scotch fillet steaks — the juiciest buffalo steak for the grill.',
    'Scotch fillet carries a little more marbling than other buffalo cuts. Sear hard on a hot pan or grill and serve medium-rare.'),
  p('water-buffalo', 'Buffalo Steaks', 'Buffalo Rib Eye Steak', '1 steak, approx. 700g, frozen', 0.7, 90,
    'A thick bone-in water buffalo rib eye — a steak to share.',
    'Cook it with a reverse sear: low heat until 50°C in the centre, then a very hot finish for the crust. Rest well and slice off the bone.',
    { badge: 'Premium' }),
  p('water-buffalo', 'Buffalo Steaks', 'Buffalo T-Bone Steak', 'approx. 800g pack, frozen', 0.8, 68.75,
    'Water buffalo T-bone steaks — sirloin and tenderloin on one bone.',
    'Keep the smaller fillet side away from the hottest part of the grill so both sides finish together. Rest for five minutes before serving.'),
  p('water-buffalo', 'Buffalo Tomahawk', 'Buffalo Tomahawk', '1 steak, approx. 900g, frozen', 0.9, 74.44,
    'A bone-in water buffalo tomahawk — a showpiece for the barbecue.',
    'Reverse-sear it: cook gently until 50°C in the centre, then finish over very high heat. Rest for ten minutes and carve off the bone to share.',
    { badge: 'Premium' }),
  p('water-buffalo', 'Diced Buffalo', 'Diced Buffalo Boneless', '2kg pack, frozen', 2, 23.5,
    'Boneless diced water buffalo for stews, curries, nihari and rendang.',
    'Lean, trimmed cubes. Brown in batches and braise slowly for two to three hours, or cook under pressure for about 40 minutes.'),
  p('water-buffalo', 'Buffalo Mince', 'Buffalo Mince', '2kg pack, frozen', 2, 17.75,
    'Lean water buffalo mince for burgers, kofta and sauces.',
    'Leaner than most beef mince with a slightly sweeter taste. Works anywhere you would use beef mince.'),
  p('water-buffalo', 'Buffalo Ribs', 'Buffalo Asado Ribs', '1kg pack, 1.2cm cut, frozen', 1, 40.5,
    'Thin-cut (1.2cm) water buffalo asado ribs for fast, hot grilling.',
    'Cut across the bones so they cook in minutes over hot coals. Season with salt or a chimichurri marinade and grill for two to three minutes a side.'),
  p('water-buffalo', 'Buffalo Osso Buco', 'Buffalo Osso Buco', '1kg pack, frozen', 1, 22,
    'Cross-cut buffalo shin with marrow for braising.',
    'Brown, then braise slowly in tomato, stock and spices for two and a half hours until the meat is soft and the marrow has melted into the sauce.'),

  // ── WHOLESALE CARTONS ─────────────────────────────────────────────────
  p('wholesale-cartons', 'Cryovac Primals', 'Beef Rump Cryovac Carton', 'approx. 20kg carton', 20, 24,
    'A carton of cryovac beef rump primals (about 20kg) for steakhouses and grill restaurants.',
    'Whole rumps in cryovac, packed by the carton for kitchens that portion their own steaks and skewers. Contact us for weekly standing orders.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Beef Mince Carton', '20kg carton', 20, 14.5,
    'A 20kg carton of beef mince for burger bars, kofta grills and takeaways.',
    'Bulk mince packed in manageable bags inside a 20kg carton. The lowest per-kilo price on mince in our range.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Lamb Curry Pieces Carton', '20kg carton', 20, 12.5,
    'A 20kg carton of bone-in lamb curry pieces for restaurants and caterers.',
    'Consistent, curry-sized lamb pieces at carton pricing — the staple for Indian, Pakistani and Afghan restaurant kitchens.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Catering Packs', 'Goat Curry Cut Catering Pack', '20kg carton', 20, 15.5,
    'A 20kg catering pack of bone-in goat curry cut for weddings, events and community functions.',
    'Enough bone-in goat for a large function, cut to a consistent curry size. Order a few days ahead for big events so we can schedule your pack.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Cryovac Primals', 'Beef Striploin Cryovac Carton', 'approx. 20kg carton', 20, 28,
    'A carton of cryovac beef striploins (about 20kg) for steakhouses and restaurants.',
    'Whole striploins in cryovac for kitchens that cut their own porterhouse steaks. Ask us about weekly standing orders.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Cryovac Primals', 'Beef Brisket Cryovac Carton', 'approx. 25kg carton', 25, 14.5,
    'A carton of cryovac beef briskets (about 25kg) for smokehouses, nihari kitchens and caterers.',
    'Whole briskets packed in cryovac by the carton. Trade pricing for kitchens that smoke or braise brisket every day.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Cryovac Primals', 'Lamb Leg Cryovac Carton', 'approx. 20kg carton', 20, 16.5,
    'A carton of cryovac bone-in lamb legs (about 20kg) for restaurants and caterers.',
    'Whole legs in cryovac for roasting, raan or breaking down into diced and curry cuts in your own kitchen.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Diced Beef Carton', '20kg carton', 20, 19,
    'A 20kg carton of boneless diced beef for curry houses, stews and catering.',
    'Even-sized boneless cubes packed in bags inside the carton, at our lowest per-kilo price on diced beef.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Lamb Shoulder Carton', '20kg carton', 20, 14.5,
    'A 20kg carton of bone-in lamb shoulders for shawarma, slow roasting and mandi.',
    'Whole shoulders at carton pricing — the go-to cut for lamb shawarma and slow-roasted restaurant dishes.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Catering Packs', 'Whole Lamb Catering Pack', '2 carcasses, approx. 40kg', 40, 15.5,
    'Two whole lambs for weddings, Eid and community events, cut to your instructions.',
    'Two carcasses cut exactly how your event needs them — curry pieces, mansaf pieces, roasts or a mix. Add cutting instructions in the order notes and order a few days ahead.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Catering Packs', 'Chicken Curry Cut Catering Pack', '20kg carton', 20, 8,
    'A 20kg catering pack of skinless bone-in chicken curry cut for large functions.',
    'Enough chicken curry cut for a big event, cut to a consistent size so every pot cooks evenly.',
    { badge: 'Trade' }),
]

export const productBySlug = (slug) => PRODUCTS.find((x) => x.slug === slug)
export const categoryBySlug = (slug) => CATEGORIES.find((c) => c.slug === slug)
export const productsInCategory = (slug) => PRODUCTS.filter((x) => x.cat === slug)
