// Product catalogue — the single source for every product page, card, sitemap
// entry, JSON-LD block, search index, MCP tool and JSON API response.
//
// Prices are AUD per pack and were set from Sydney halal-butcher market research
// (October 2026, see docs/PROJECT.md → "Pricing basis"), discounted for depot
// bulk packs. The owner should review them before launch.
//
// Images: every product points at /images/products/<slug>-<IMAGE_VERSION>.webp.
// Bump IMAGE_VERSION whenever images are regenerated so no cache serves old ones. Until real
// photos are supplied, scripts/images.mjs generates a branded placeholder at
// that exact path — dropping a real photo into assets/product-photos/<slug>.jpg
// and running `npm run images` replaces it with no code change.

export const IMAGE_VERSION = 'v2'
export const categoryImage = (slug) => `${slug}-${IMAGE_VERSION}.webp`

export const CATEGORIES = [
  {
    slug: 'beef',
    name: 'Beef',
    kw: 'halal beef',
    tagline: 'Primals, steaks, mince, Wagyu and soup bones',
    intro:
      'Halal beef for home kitchens, grill restaurants and caterers — from whole eye fillets and rumps to bulk mince, diced beef and Wagyu marble score 8–9. Every cut is packed in vacuum-sealed packs at depot prices and certified halal by Halal Control Australia.',
    subcategories: [
      'Primal Cuts & Loins',
      'Scotch & Ribeye Steaks',
      'Porterhouse & T-Bone',
      'Briskets & Short Ribs',
      'Mince, Diced & Stir-Fry',
      'Wagyu MB7+ & MB9+',
      'Shanks, Oxtail & Soup Bones',
    ],
  },
  {
    slug: 'lamb',
    name: 'Lamb',
    kw: 'halal lamb',
    tagline: 'Whole carcasses, cutlets, legs, shanks and curry cuts',
    intro:
      'Halal lamb by the carcass, the leg or the kilo. Choose whole and half lamb for family events, frenched cutlets and loin chops for the grill, or bone-in curry pieces and boneless diced lamb for slow cooking — all certified halal by Halal Control Australia.',
    subcategories: [
      'Whole & Half Carcass',
      'Frenched Cutlets & Loin Chops',
      'Forequarter & Hindquarter',
      'Easy-Carve Leg of Lamb',
      'Lamb Shanks & Shoulders',
      'Bone-in Curry & Biryani Cuts',
      'Boneless Diced & Mince',
    ],
  },
  {
    slug: 'goat',
    name: 'Goat',
    kw: 'halal goat meat',
    tagline: 'Whole goat, curry cut, diced, legs, chops and shanks',
    intro:
      'Halal goat meat for curries, biryani, mandi and roasts. Buy a whole goat carcass, bone-in curry cut in 5kg packs, lean boneless diced goat, or legs, shoulders, cutlets and shanks — certified halal by Halal Control Australia and delivered Australia-wide.',
    subcategories: [
      'Whole Goat Carcass',
      'Bone-in Curry Cut',
      'Boneless Diced Goat',
      'Goat Leg & Shoulder Roasts',
      'Goat Chops & Ribs',
      'Goat Shanks & Stew Pieces',
    ],
  },
  {
    slug: 'chicken',
    name: 'Chicken',
    kw: 'halal chicken',
    tagline: 'Whole birds, fillets, drumsticks, wings and bulk cartons',
    intro:
      'Halal chicken in household packs and commercial cartons: whole birds, skinless breast and thigh fillets, drumsticks, wings, bone-in curry cut and free-range birds. 10kg cartons suit takeaways and caterers. All chicken is certified halal by Halal Control Australia.',
    subcategories: [
      'Whole Broiler & Roasting Birds',
      'Skinless Breast Fillets',
      'Thigh Fillets & Cutlets',
      'Drumsticks & Wings',
      'Bone-in Curry & Biryani Cuts',
      'Corn-Fed & Free-Range Birds',
      'Bulk Commercial Cartons',
    ],
  },
  {
    slug: 'camel',
    name: 'Camel',
    kw: 'halal camel meat',
    tagline: 'Curry pieces, diced, steaks, hump, mince and ribs',
    intro:
      'Halal camel meat is lean, rich in iron and a staple of Middle Eastern, Somali and North African cooking. We stock bone-in curry pieces, boneless diced camel, striploin and rump steaks, traditional hump, mince and ribs — certified halal by Halal Control Australia.',
    subcategories: [
      'Bone-in Camel Curry Pieces',
      'Boneless Diced Camel Meat',
      'Camel Striploin & Rump Steaks',
      'Traditional Camel Hump',
      'Lean Camel Mince',
      'Camel Ribs & Shoulder Roasts',
    ],
  },
  {
    slug: 'duck',
    name: 'Duck',
    kw: 'halal duck',
    tagline: 'Whole Pekin ducks, breasts, marylands, wings and giblets',
    intro:
      'Halal duck for roasting, braising and special occasions. Order whole Pekin ducks, skin-on breast fillets, duck marylands for confit, wings for the grill and giblets for stock — every pack certified halal by Halal Control Australia.',
    subcategories: [
      'Whole Pekin Ducks',
      'Duck Breast Fillets',
      'Duck Maryland & Legs',
      'Duck Wings & Portions',
      'Duck Giblets',
    ],
  },
  {
    slug: 'kangaroo',
    name: 'Kangaroo',
    kw: 'halal kangaroo meat',
    tagline: 'Fillets, steaks, diced, mince and tail',
    intro:
      'Kangaroo is one of the leanest red meats available — high in protein and iron, low in fat. Our halal kangaroo range covers fillets, steaks, diced meat for stews, lean mince and tail for slow braising, all certified halal by Halal Control Australia.',
    subcategories: [
      'Kangaroo Fillet & Medallions',
      'Kangaroo Steaks',
      'Diced Kangaroo',
      'Lean Kangaroo Mince',
      'Kangaroo Tail',
    ],
  },
  {
    slug: 'water-buffalo',
    name: 'Water Buffalo',
    kw: 'halal buffalo meat',
    tagline: 'Striploin, curry cut, diced, short ribs, mince and osso buco',
    intro:
      'Water buffalo is a lean red meat with a clean, slightly sweet flavour that suits both quick grilling and long braising. Shop halal buffalo striploin steaks, bone-in curry cut, diced meat, short ribs, mince and osso buco — certified halal by Halal Control Australia.',
    subcategories: [
      'Buffalo Striploin Steaks',
      'Bone-in Buffalo Curry Cut',
      'Boneless Diced Buffalo',
      'Buffalo Short Ribs',
      'Buffalo Mince',
      'Buffalo Osso Buco',
    ],
  },
  {
    slug: 'wholesale-cartons',
    name: 'Wholesale Cartons',
    kw: 'wholesale halal meat',
    tagline: 'Cryovac primals, restaurant cartons and catering packs',
    intro:
      'Wholesale halal meat cartons for restaurants, takeaways, caterers and community events. Cryovac beef primals, 20kg lamb and goat curry-cut cartons and 20kg beef mince are priced per carton for trade buyers. For weekly volume pricing, open a wholesale account.',
    subcategories: ['Cryovac Primals', 'Restaurant Bulk Cartons', 'Catering Packs'],
  },
]

// p(category, subcategory, name, packLabel, packKg, perKg, short, desc, extra)
function p(cat, sub, name, unit, kg, perKg, short, desc, extra = {}) {
  const slug = extra.slug || name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  return {
    slug,
    name,
    cat,
    sub,
    unit,
    kg,
    perKg,
    price: Math.round(kg * perKg * 100) / 100,
    short,
    desc,
    badge: extra.badge || null,
    featured: Boolean(extra.featured),
    images: [`${slug}-${IMAGE_VERSION}.webp`],
  }
}

export const PRODUCTS = [
  // ── BEEF ──────────────────────────────────────────────────────────────
  p('beef', 'Primal Cuts & Loins', 'Beef Eye Fillet Whole', 'approx. 2kg whole piece', 2, 52,
    'Whole beef eye fillet (tenderloin) — the most tender cut on the animal, ready to trim into steaks or roast whole.',
    'A whole eye fillet gives you the best value per steak: cut it into medallions, tie the centre for a roast, and use the tail for stir-fry or skewers. Vacuum-sealed whole so you portion it exactly how your kitchen needs.',
    { badge: 'Premium', featured: true }),
  p('beef', 'Primal Cuts & Loins', 'Beef Rump Whole', 'approx. 4kg whole piece', 4, 26,
    'Whole beef rump primal with cap, a flavourful all-rounder for steaks, roasts and grilling.',
    'Rump is the workhorse of steak restaurants — firm, beefy and forgiving on the grill. Separate the cap for picanha-style skewers, slice the centre into rump steaks and dice the trim for kebabs.'),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Scotch Fillet Steaks', '2kg pack', 2, 42,
    'Boneless scotch fillet steaks cut from the rib, well marbled for juicy pan-searing and barbecue.',
    'Scotch fillet carries more intramuscular fat than most steaks, which keeps it juicy at medium and above. Sear hard on a hot pan or grill, rest for five minutes and slice against the grain.',
    { badge: 'Popular', featured: true }),
  p('beef', 'Scotch & Ribeye Steaks', 'Beef Rib Eye on the Bone', '2kg pack', 2, 38,
    'Bone-in rib eye steaks — thick, marbled and made for charcoal grilling.',
    'Cooking on the bone protects the meat and adds flavour. These thick-cut rib eyes suit a reverse sear: low heat until 50°C inside, then a fast, very hot finish for the crust.'),
  p('beef', 'Porterhouse & T-Bone', 'Beef Porterhouse Steaks', '2kg pack', 2, 34,
    'Porterhouse (sirloin) steaks with a firm texture and a strip of fat for flavour.',
    'Porterhouse is the classic grill steak — lean through the centre with a fat cap that renders as it cooks. Score the fat, season well and cook to medium-rare for the best texture.'),
  p('beef', 'Porterhouse & T-Bone', 'Beef T-Bone Steaks', '2kg pack', 2, 32,
    'T-bone steaks combining sirloin and a piece of tenderloin on one bone.',
    'Two steaks in one: the sirloin side gives bite and flavour, the smaller fillet side melts. Keep the fillet side away from the hottest part of the grill so both finish together.'),
  p('beef', 'Briskets & Short Ribs', 'Beef Brisket Whole', 'approx. 5kg whole piece', 5, 16,
    'Whole beef brisket with point and flat — for smoking, slow braising and nihari.',
    'Brisket needs time: eight to twelve hours of low smoke, or three to four hours braised, turns the connective tissue into gelatine. Trim the fat cap to about 5mm before cooking.',
    { badge: 'Best Value' }),
  p('beef', 'Briskets & Short Ribs', 'Beef Short Ribs', '2kg pack', 2, 22,
    'Meaty beef short ribs for braising, smoking and Korean-style grilling.',
    'Short ribs are rich and generously marbled. Braise them in stock and spices until the meat pulls from the bone, or smoke them low and slow as a weekend centrepiece.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Premium Beef Mince', '5kg pack', 5, 15.5,
    'Premium beef mince in a 5kg pack — for kofta, burgers, pasta sauces and keema.',
    'A lean-to-fat balance that holds together for kofta and burgers without drying out. The 5kg pack is portioned for freezing, so it suits both busy households and small takeaways.',
    { badge: 'Popular', featured: true }),
  p('beef', 'Mince, Diced & Stir-Fry', 'Diced Beef Boneless', '3kg pack', 3, 21,
    'Boneless diced beef cut into even pieces for curries, stews and casseroles.',
    'Even-sized cubes cook at the same rate, so every piece is tender at the same time. Brown in batches for the deepest flavour before adding liquid.'),
  p('beef', 'Mince, Diced & Stir-Fry', 'Beef Stir-Fry Strips', '2kg pack', 2, 23,
    'Thin beef strips sliced across the grain for fast stir-fries, fajitas and shawarma-style wraps.',
    'Sliced thin and across the grain so the strips stay tender after a quick, hot cook. Marinate for 30 minutes, then cook in small batches so the pan stays hot.'),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Scotch Fillet MB8-9', '1kg pack', 1, 95,
    'Wagyu scotch fillet with marble score 8–9 — intensely marbled for special occasions.',
    'At marble score 8–9 the fat is spread through the muscle in fine flecks, giving a buttery texture. Cut thinner steaks (about 2cm), sear briefly and serve in small portions.',
    { badge: 'Premium', featured: true }),
  p('beef', 'Wagyu MB7+ & MB9+', 'Wagyu Brisket MB9+', 'approx. 5kg whole piece', 5, 34,
    'Marble score 9+ Wagyu brisket — the richest brisket for smoking and braising.',
    'High marbling keeps Wagyu brisket moist through a long smoke. It renders more fat than standard brisket, so trim the cap a little more and wrap once the bark has set.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Osso Buco', '3kg pack', 3, 14.5,
    'Cross-cut beef shin with marrow bone for osso buco, stews and paya-style broths.',
    'The marrow melts into the sauce and the shin meat turns silky after two to three hours of gentle braising. Tie each piece with string to keep it neat in the pot.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Oxtail', '2kg pack', 2, 24,
    'Beef oxtail pieces for rich soups, stews and slow-cooked curries.',
    'Oxtail is mostly bone and collagen, which gives soups and stews a deep, glossy body. Brown well, then simmer for three hours or pressure-cook for about 50 minutes.'),
  p('beef', 'Shanks, Oxtail & Soup Bones', 'Beef Soup Bones', '5kg pack', 5, 5.5,
    'Beef marrow and knuckle bones for stock, broth and soup.',
    'Roast the bones at 220°C until browned, then simmer with onion and spices for six hours or more for a clear, full-bodied stock that freezes well.'),

  // ── LAMB ──────────────────────────────────────────────────────────────
  p('lamb', 'Whole & Half Carcass', 'Whole Lamb Carcass', 'approx. 20kg carcass', 20, 16.5,
    'A whole lamb carcass, cut to your instructions — ideal for family events and gatherings.',
    'Order a whole lamb and tell us how you want it cut: curry pieces, roasts, chops, or a mix. Add your cutting instructions in the order notes at checkout.',
    { badge: 'Best Value', featured: true }),
  p('lamb', 'Whole & Half Carcass', 'Half Lamb Carcass', 'approx. 10kg half carcass', 10, 17,
    'Half a lamb carcass, cut to your instructions — a full mix of roasts, chops and curry cuts.',
    'A practical way to stock the freezer: half a lamb typically yields a leg, a shoulder, chops, shanks and a good quantity of curry pieces. Specify your cuts in the order notes.'),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Cutlets Frenched', '1kg pack', 1, 46,
    'Frenched lamb cutlets with the rib bone cleaned — elegant, tender and quick to cook.',
    'Cutlets need only two to three minutes a side on a hot grill. Season simply with salt, garlic and rosemary, or marinate in yoghurt and spices for a tandoori-style finish.',
    { badge: 'Premium' }),
  p('lamb', 'Frenched Cutlets & Loin Chops', 'Lamb Loin Chops', '2kg pack', 2, 30,
    'Lamb loin chops — tender, meaty and perfect for the barbecue.',
    'Loin chops have a small T-shaped bone with tender loin on one side. Grill over high heat and rest briefly; they are at their best pink in the middle.'),
  p('lamb', 'Forequarter & Hindquarter', 'Lamb Forequarter Chops', '3kg pack', 3, 17,
    'Lamb forequarter chops — flavourful, budget-friendly chops for grilling and braising.',
    'Forequarter chops have more connective tissue than loin chops, which means more flavour. Grill them hot and fast, or braise in a tomato and spice sauce until tender.'),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Leg Bone-in', 'approx. 2.5kg whole leg', 2.5, 19,
    'Whole bone-in leg of lamb for roasting, raan and slow cooking.',
    'Stud the leg with garlic, rub with spices and roast at 180°C — allow about 25 minutes per kilo for pink, or slow-roast for five hours until it falls from the bone.',
    { featured: true }),
  p('lamb', 'Easy-Carve Leg of Lamb', 'Lamb Leg Boneless', 'approx. 2kg rolled leg', 2, 24,
    'Boneless leg of lamb, rolled and netted for easy carving.',
    'With the bone removed the leg cooks evenly and carves into neat slices. Unroll it to stuff with herbs and garlic, or butterfly it flat for the barbecue.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shanks', '2kg pack', 2, 20,
    'Lamb shanks for slow braising — tender, gelatinous and full of flavour.',
    'Braise shanks for two and a half to three hours in a covered pot until the meat slides off the bone. They reheat beautifully, so cook a big batch.'),
  p('lamb', 'Lamb Shanks & Shoulders', 'Lamb Shoulder Bone-in', 'approx. 2.5kg whole shoulder', 2.5, 16,
    'Bone-in lamb shoulder for slow roasting, shawarma and pulled lamb.',
    'Shoulder has more fat and connective tissue than the leg, which makes it ideal for long, slow cooking. Roast covered at 150°C for four to five hours and pull apart with forks.'),
  p('lamb', 'Bone-in Curry & Biryani Cuts', 'Lamb Curry Pieces', '5kg pack', 5, 13.5,
    'Bone-in lamb curry pieces, cut through the bone for curries, biryani and mansaf.',
    'Cutting through the bone releases marrow and collagen into the sauce, giving curries more body. Pieces are cut to a consistent size so they cook evenly.',
    { badge: 'Popular', featured: true }),
  p('lamb', 'Boneless Diced & Mince', 'Diced Lamb Boneless', '3kg pack', 3, 27,
    'Boneless diced lamb for kebabs, curries and stews.',
    'Trimmed and cut into even cubes. For skewers, marinate overnight in yoghurt, lemon and spices; for curries, brown well before adding the sauce.'),
  p('lamb', 'Boneless Diced & Mince', 'Lamb Mince', '3kg pack', 3, 16,
    'Lamb mince for kofta, kibbeh, keema and meatballs.',
    'Lamb mince carries more flavour than beef and suits warm spices. Mix with onion, parsley and allspice for kofta, or brown with garam masala for keema.'),

  // ── GOAT ──────────────────────────────────────────────────────────────
  p('goat', 'Whole Goat Carcass', 'Whole Goat Carcass', 'approx. 12kg carcass', 12, 17.5,
    'A whole young goat carcass, cut to your instructions for curries, roasts and events.',
    'A whole goat is the most economical way to buy for large gatherings. Tell us your preferred cuts — curry pieces, legs, shoulders, chops — in the order notes.',
    { badge: 'Best Value', featured: true }),
  p('goat', 'Bone-in Curry Cut', 'Goat Curry Cut Bone-in', '5kg pack', 5, 16.5,
    'Bone-in goat curry cut — the classic choice for curries, biryani, karahi and mandi.',
    'Mixed pieces from across the carcass, cut through the bone for rich, full-bodied curries. Allow about 90 minutes of gentle simmering, or 30 minutes in a pressure cooker.',
    { badge: 'Popular', featured: true }),
  p('goat', 'Boneless Diced Goat', 'Diced Goat Boneless', '3kg pack', 3, 27,
    'Lean boneless diced goat for stews, curries and skewers.',
    'All the flavour of goat without the bones. Goat is lean, so cook it gently — slow simmering or a long marinade before grilling keeps it tender.'),
  p('goat', 'Goat Leg & Shoulder Roasts', 'Goat Leg Bone-in', 'approx. 2kg whole leg', 2, 24,
    'Bone-in goat leg for slow roasting and festive dishes.',
    'Marinate overnight in yoghurt, garlic and spices, then roast covered at 160°C for three hours. The meat should pull easily from the bone.'),
  p('goat', 'Goat Leg & Shoulder Roasts', 'Goat Shoulder Bone-in', 'approx. 2kg whole shoulder', 2, 21,
    'Bone-in goat shoulder for slow-cooked roasts and pulled goat.',
    'The shoulder has more marbling than the leg and stays succulent through long cooking. Ideal for mandi-style slow roasting.'),
  p('goat', 'Goat Chops & Ribs', 'Goat Cutlets and Chops', '2kg pack', 2, 33,
    'Goat cutlets and chops for grilling and pan-frying.',
    'Tender chops from the rack and loin. Marinate for a few hours and grill over medium-high heat — goat is lean, so avoid overcooking.'),
  p('goat', 'Goat Chops & Ribs', 'Goat Ribs', '2kg pack', 2, 18,
    'Goat ribs for slow grilling, braising and soups.',
    'Ribs carry a good amount of fat for goat, so they crisp nicely after a slow cook. Braise until tender, then finish on a hot grill.'),
  p('goat', 'Goat Shanks & Stew Pieces', 'Goat Shanks and Stew Pieces', '3kg pack', 3, 17,
    'Goat shanks and stew pieces for slow-cooked soups and stews.',
    'Collagen-rich pieces that turn soft and sticky after two hours of slow cooking. A great base for paya, nihari-style stews and hearty soups.'),

  // ── CHICKEN ───────────────────────────────────────────────────────────
  p('chicken', 'Whole Broiler & Roasting Birds', 'Whole Chickens Size 16', '10 birds, approx. 16kg', 16, 7,
    'Ten whole chickens (size 16, about 1.6kg each) for roasting, charcoal chicken and curries.',
    'A carton of ten size-16 birds suits large families, charcoal chicken shops and caterers. Roast at 200°C for about 75 minutes, or butterfly for the grill.',
    { badge: 'Best Value', featured: true }),
  p('chicken', 'Skinless Breast Fillets', 'Chicken Breast Fillets', '5kg pack', 5, 12.5,
    'Skinless chicken breast fillets for grilling, schnitzel, stir-fries and wraps.',
    'Lean and versatile. Butterfly or pound thick fillets to an even thickness so they cook through without drying out.',
    { badge: 'Popular', featured: true }),
  p('chicken', 'Thigh Fillets & Cutlets', 'Chicken Thigh Fillets', '5kg pack', 5, 14,
    'Boneless, skinless chicken thigh fillets — juicy and forgiving for shish, curries and shawarma.',
    'Thigh fillets stay moist even when cooked over high heat, which is why most kebab and shawarma kitchens prefer them to breast.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Drumsticks', '5kg pack', 5, 5.5,
    'Chicken drumsticks for roasting, frying and the barbecue.',
    'Economical and family-friendly. Score the meat and marinate overnight, then bake at 200°C for 40 minutes or grill over medium heat.'),
  p('chicken', 'Drumsticks & Wings', 'Chicken Wings', '5kg pack', 5, 5,
    'Whole chicken wings for frying, baking and grilling.',
    'Pat dry and bake on a rack at 220°C for crisp skin, or fry and toss in sauce. Separate into drumettes and wingettes if you prefer.'),
  p('chicken', 'Bone-in Curry & Biryani Cuts', 'Chicken Curry Cut Bone-in', '5kg pack', 5, 9,
    'Skinless bone-in chicken curry cut for curries, biryani and karahi.',
    'Whole birds cut into curry-sized pieces with the skin removed, so the masala reaches the meat. Ready to cook straight from the pack.'),
  p('chicken', 'Corn-Fed & Free-Range Birds', 'Free-Range Whole Chickens', '4 birds, approx. 7.2kg', 7.2, 10.5,
    'Four free-range whole chickens (about 1.8kg each) for roasting.',
    'Free-range birds have a firmer texture and fuller flavour. Roast whole with lemon and garlic, or spatchcock for faster, even cooking.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Breast Fillet Carton', '10kg carton', 10, 11.5,
    'A 10kg carton of skinless chicken breast fillets for takeaways and caterers.',
    'Commercial carton pricing for kitchens that go through breast fillet every day. Fillets are packed in bags inside the carton for easier portioning.'),
  p('chicken', 'Bulk Commercial Cartons', 'Chicken Thigh Fillet Carton', '10kg carton', 10, 13,
    'A 10kg carton of boneless chicken thigh fillets for shawarma, shish and grills.',
    'The go-to cut for shawarma cones and charcoal skewers, at carton pricing. Ideal for restaurants that marinate in bulk.'),

  // ── CAMEL ─────────────────────────────────────────────────────────────
  p('camel', 'Bone-in Camel Curry Pieces', 'Camel Curry Pieces Bone-in', '3kg pack', 3, 22,
    'Bone-in camel curry pieces for stews, curries, kabsa and mandi.',
    'Camel is lean with a slightly sweet flavour. Bone-in pieces give the sauce body — simmer gently for two to three hours or pressure-cook for about 45 minutes.',
    { featured: true }),
  p('camel', 'Boneless Diced Camel Meat', 'Diced Camel Boneless', '2kg pack', 2, 32,
    'Boneless diced camel meat for stews, suqaar and slow-cooked dishes.',
    'Trimmed, boneless camel ready for the pot. For Somali-style suqaar, cut smaller and stir-fry with onion, capsicum and spices.'),
  p('camel', 'Camel Striploin & Rump Steaks', 'Camel Striploin Steaks', '1kg pack', 1, 42,
    'Camel striploin steaks — lean, tender steaks for quick grilling.',
    'Camel steaks are very lean, so cook them quickly over high heat to medium-rare and rest well. A light oil marinade helps keep them juicy.'),
  p('camel', 'Traditional Camel Hump', 'Camel Hump', 'approx. 1kg piece', 1, 28,
    'Camel hump — the traditional fatty cut, prized for flavour and for cooking with lean camel meat.',
    'The hump is mostly fat and is traditionally diced and cooked alongside lean camel meat, or rendered for cooking fat. Use in small amounts — a little goes a long way.'),
  p('camel', 'Lean Camel Mince', 'Camel Mince', '2kg pack', 2, 26,
    'Lean camel mince for burgers, kofta and stuffed vegetables.',
    'Very lean mince with a mild, slightly sweet flavour. Add grated onion or a little camel hump fat to keep burgers and kofta moist.'),
  p('camel', 'Camel Ribs & Shoulder Roasts', 'Camel Ribs and Shoulder', 'approx. 2.5kg pack', 2.5, 20,
    'Camel ribs and shoulder for slow roasting and braising.',
    'Cuts that reward patience: braise covered for three to four hours with spices and stock until tender, then finish uncovered to brown.'),

  // ── DUCK ──────────────────────────────────────────────────────────────
  p('duck', 'Whole Pekin Ducks', 'Whole Pekin Ducks', '2 ducks, approx. 4.4kg', 4.4, 14,
    'Two whole Pekin ducks (about 2.2kg each) for roasting and braising.',
    'Prick the skin, season generously and roast at 180°C for about two hours, pouring off the fat as it renders. Save the fat — it makes exceptional roast potatoes.',
    { featured: true }),
  p('duck', 'Duck Breast Fillets', 'Duck Breast Fillets Skin-on', '1kg pack', 1, 42,
    'Skin-on duck breast fillets — score, render and serve pink.',
    'Start skin-side down in a cold pan and cook gently for eight to ten minutes to render the fat, then turn for two minutes. Rest and slice.'),
  p('duck', 'Duck Maryland & Legs', 'Duck Maryland', '2kg pack', 2, 26,
    'Duck marylands (thigh and drumstick) for confit, braising and roasting.',
    'The leg is the most forgiving part of the duck. Slow-cook in its own fat for confit, or braise with orange and spices until the meat falls away.'),
  p('duck', 'Duck Wings & Portions', 'Duck Wings', '2kg pack', 2, 12,
    'Duck wings for grilling, braising and stock.',
    'Rich wings that are excellent braised with ginger, garlic and warm spices or roasted until sticky. They also make a deep, flavourful stock.'),
  p('duck', 'Duck Giblets', 'Duck Giblets', '1kg pack', 1, 12,
    'Duck hearts, gizzards and necks for stock, gravy and traditional dishes.',
    'Giblets add depth to stocks and gravies. Gizzards can be slow-cooked until tender and then pan-fried with garlic and spices.'),

  // ── KANGAROO ──────────────────────────────────────────────────────────
  p('kangaroo', 'Kangaroo Fillet & Medallions', 'Kangaroo Fillet', '1kg pack', 1, 29,
    'Kangaroo fillet — a very lean, tender red meat for searing and grilling.',
    'With under 2% fat, kangaroo fillet must be cooked quickly: sear for two to three minutes a side to rare or medium-rare and rest well before slicing.',
    { featured: true }),
  p('kangaroo', 'Kangaroo Steaks', 'Kangaroo Steaks', '1kg pack', 1, 26,
    'Kangaroo steaks — lean, rich-tasting steaks for the grill.',
    'Oil the meat rather than the pan, cook over high heat and stop at medium-rare. Overcooking is the only way to make kangaroo tough.'),
  p('kangaroo', 'Diced Kangaroo', 'Diced Kangaroo', '2kg pack', 2, 22,
    'Diced kangaroo for slow-cooked stews, curries and casseroles.',
    'For slow cooking, keep the heat low and the lid on — kangaroo becomes tender after about 90 minutes of gentle simmering.'),
  p('kangaroo', 'Lean Kangaroo Mince', 'Kangaroo Mince', '2kg pack', 2, 18,
    'Lean kangaroo mince for burgers, bolognese and kofta.',
    'One of the leanest minces available. Add a little oil or finely grated vegetables to burgers and meatballs to keep them moist.'),
  p('kangaroo', 'Kangaroo Tail', 'Kangaroo Tail', '2kg pack', 2, 14,
    'Kangaroo tail pieces for soups and slow braises.',
    'Like oxtail, kangaroo tail is rich in collagen. Braise for three hours or more for a deeply flavoured, glossy stew.'),

  // ── WATER BUFFALO ─────────────────────────────────────────────────────
  p('water-buffalo', 'Buffalo Striploin Steaks', 'Buffalo Striploin Steaks', '1kg pack', 1, 45,
    'Water buffalo striploin steaks — lean, tender and slightly sweet.',
    'Buffalo has less fat than beef, so it cooks faster. Grill to medium-rare over high heat and rest for five minutes.',
    { featured: true }),
  p('water-buffalo', 'Bone-in Buffalo Curry Cut', 'Buffalo Curry Cut Bone-in', '3kg pack', 3, 19,
    'Bone-in buffalo curry cut for curries, stews and nihari.',
    'Bone-in pieces that simmer into rich, full-bodied curries. Allow two hours of gentle cooking, or about 40 minutes under pressure.'),
  p('water-buffalo', 'Boneless Diced Buffalo', 'Diced Buffalo Boneless', '2kg pack', 2, 28,
    'Boneless diced buffalo for stews, curries and skewers.',
    'Lean, trimmed cubes. Marinate before grilling, or brown and braise slowly for a tender stew.'),
  p('water-buffalo', 'Buffalo Short Ribs', 'Buffalo Short Ribs', '2kg pack', 2, 24,
    'Buffalo short ribs for braising and slow smoking.',
    'Meaty ribs with a clean flavour. Braise for three hours or smoke low and slow until the meat pulls cleanly from the bone.'),
  p('water-buffalo', 'Buffalo Mince', 'Buffalo Mince', '2kg pack', 2, 22,
    'Lean buffalo mince for burgers, kofta and sauces.',
    'Leaner than most beef mince with a slightly sweeter taste. Works anywhere you would use beef mince.'),
  p('water-buffalo', 'Buffalo Osso Buco', 'Buffalo Osso Buco', '2kg pack', 2, 19,
    'Cross-cut buffalo shin with marrow for braising.',
    'Brown, then braise slowly in tomato, stock and spices for two and a half hours until the meat is soft and the marrow has melted into the sauce.'),

  // ── WHOLESALE CARTONS ─────────────────────────────────────────────────
  p('wholesale-cartons', 'Cryovac Primals', 'Beef Rump Cryovac Carton', 'approx. 20kg carton', 20, 24,
    'A carton of cryovac beef rump primals (about 20kg) for steakhouses and grill restaurants.',
    'Whole rumps in cryovac, packed by the carton for kitchens that portion their own steaks and skewers. Contact us for weekly standing orders.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Beef Mince Carton', '20kg carton', 20, 14.5,
    'A 20kg carton of beef mince for burger bars, kofta grills and takeaways.',
    'Bulk mince packed in manageable bags inside a 20kg carton. The lowest per-kilo price on mince in our range.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Restaurant Bulk Cartons', 'Lamb Curry Pieces Carton', '20kg carton', 20, 12.5,
    'A 20kg carton of bone-in lamb curry pieces for restaurants and caterers.',
    'Consistent, curry-sized lamb pieces at carton pricing — the staple for Indian, Pakistani and Afghan restaurant kitchens.',
    { badge: 'Trade' }),
  p('wholesale-cartons', 'Catering Packs', 'Goat Curry Cut Catering Pack', '20kg carton', 20, 15.5,
    'A 20kg catering pack of bone-in goat curry cut for weddings, events and community functions.',
    'Enough bone-in goat for a large function, cut to a consistent curry size. Order a few days ahead for big events so we can schedule your pack.',
    { badge: 'Trade' }),
]

export const productBySlug = (slug) => PRODUCTS.find((x) => x.slug === slug)
export const categoryBySlug = (slug) => CATEGORIES.find((c) => c.slug === slug)
export const productsInCategory = (slug) => PRODUCTS.filter((x) => x.cat === slug)
